# Generated by Django 3.1.5 on 2021-06-27 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='osobe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('broj_indeksa', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
                ('ime', models.CharField(max_length=15)),
                ('prezime', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('datum_kreiranja', models.DateField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='kolegiji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_kolegija', models.CharField(max_length=40)),
                ('akademska_godina', models.CharField(choices=[('1. godina', '1. godina'), ('2. godina', '2. godina'), ('3. godina', '3. godina'), ('4. godina', '4. godina'), ('5. godina', '5. godina')], default='1. godina', max_length=9)),
                ('osobeFK', models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='studij',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_studija', models.CharField(max_length=40)),
                ('godina_studija', models.CharField(choices=[('1. godina', '1. godina'), ('2. godina', '2. godina'), ('3. godina', '3. godina'), ('4. godina', '4. godina'), ('5. godina', '5. godina')], default='1. godina', max_length=9)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ucionica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_ucionice', models.IntegerField()),
                ('broj_mjesta', models.IntegerField()),
                ('kat', models.IntegerField()),
                ('slobodna_ucionica', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='uloga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=15)),
                ('datum_dodjele', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='termini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now=True)),
                ('vrijeme_pocetka', models.TimeField()),
                ('zavrsetak', models.TimeField()),
                ('trajanje', models.DurationField()),
                ('broj_ucionce_fk', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='diplomskirad.ucionica')),
                ('naziv_kolegija', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='diplomskirad.kolegiji')),
                ('studij_fk', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='diplomskirad.studij')),
            ],
        ),
        migrations.CreateModel(
            name='evidencija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osoba_fk', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('predavanja_fk', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='diplomskirad.termini')),
            ],
        ),
    ]
