# Generated by Django 3.1.5 on 2021-06-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diplomskirad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osobe',
            name='ulogaFK',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='diplomskirad.uloga'),
        ),
    ]
